options
availableOptions
  ^ super availableOptions
    ,
      {'archive'.
      'back'.
      ('changeModification' -> 'chmod').
      ('columnWidth' -> 'colwidth').
      'copy'.
      'cut'.
      'download'.
      'duplicate'.
      'edit'.
      'extract'.
      'forward'.
      ('fullScreen' -> 'fullscreen').
      ('getFile' -> 'getfile').
      'help'.
      'home'.
      'info'.
      ('makeDirectory' -> 'mkdir').
      ('makeFile' -> 'mkfile').
      ('netMount' -> 'netmount').
      ('newUnmount' -> 'netunmount').
      'open'.
      ('openDirectory' -> 'opendir').
      'paste'.
      'places'.
      ('quickLook' -> 'quicklook').
      'reload'.
      'rename'.
      'resize'.
      ('remove' -> 'rm').
      'search'.
      'sort'.
      'up'.
      'upload'.
      'view'}