configuration
configurationOptions
  ^ {(ElFinderOption key: 'archive').
  (ElFinderOption key: 'back').
  (ElFinderOption key: 'chmod' selector: #'changeModification').
  (ElFinderOption key: 'copy').
  (ElFinderOption key: 'cut').
  (ElFinderOption key: 'download').
  (ElFinderOption key: 'duplicate').
  (ElFinderOption key: 'edit').
  (ElFinderOption key: 'extract').
  (ElFinderOption key: 'forward').
  (ElFinderOption key: 'fullscreen' selector: #'fullScreen').
  (ElFinderOption key: 'getfile' selector: #'getFile').
  (ElFinderOption key: 'help').
  (ElFinderOption key: 'home').
  (ElFinderOption key: 'info').
  (ElFinderOption key: 'mkdir' selector: #'makeDirectory').
  (ElFinderOption key: 'mkfile' selector: #'makeFile').
  (ElFinderOption key: 'netmount' selector: #'netMount').
  (ElFinderOption key: 'netunmount' selector: #'netUnmount').
  (ElFinderOption key: 'open').
  (ElFinderOption key: 'opendir' selector: #'openDirectory').
  (ElFinderOption key: 'paste').
  (ElFinderOption key: 'places').
  (ElFinderOption key: 'quicklook' selector: #'quickLook').
  (ElFinderOption key: 'reload').
  (ElFinderOption key: 'rename').
  (ElFinderOption key: 'resize').
  (ElFinderOption key: 'rm' selector: #'remove').
  (ElFinderOption key: 'search').
  (ElFinderOption key: 'sort').
  (ElFinderOption key: 'up').
  (ElFinderOption key: 'upload').
  (ElFinderOption key: 'view')}